# Generated by Django 3.2 on 2021-05-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapp01', '0006_alter_newuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='password2',
            new_name='confirm_password',
        ),
    ]
