# Generated by Django 3.2 on 2021-05-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelapp01', '0007_rename_password2_newuser_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
